### ISSUE TITLE
Can you please provide a dataset categorized by task? 

### ISSUE THREAD

**Issue by qqiuqq** [Luo-Z13/SkySenseGPT#2]
Can you please provide a dataset categorized by task? Like in the article. Right now this organization leads me to not know which task this one conversation belongs to.
![20240720-105540](https://github.com/user-attachments/assets/0f67f2f9-137a-43db-b876-73ff2de9e877)

**Comment by Luo-Z13** [comment]
> Can you please provide a dataset categorized by task? Like in the article. Right now this organization leads me to not know which task this one conversation belongs to. ![20240720-105540](https://private-user-images.githubusercontent.com/113153117/350658090-0f67f2f9-137a-43db-b876-73ff2de9e877.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0NTI0NTAsIm5iZiI6MTcyMTQ1MjE1MCwicGF0aCI6Ii8xMTMxNTMxMTcvMzUwNjU4MDkwLTBmNjdmMmY5LTEzN2EtNDNkYi1iODc2LTczZmYyZGU5ZTg3Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMFQwNTA5MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MDAyMDlkOTBlYmMzNDhjOWJlOWNmZTFlYTg2YWUxMGVkMzE2MmFkNjdlODFlYmMyNmY4ZTRlYzBhZGM0NTYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qw9EH3VMABqIMOxDdrU6hn_Q0VUahTGPluQvlui57xs)

Of course, they have been uploaded into https://huggingface.co/datasets/ll-13/FIT-RS/blob/main/FIT-RS_Instruction/train_data_of_each_individual_task.zip.

**Comment by qqiuqq** [comment]
> > Can you please provide a dataset categorized by task? Like in the article. Right now this organization leads me to not know which task this one conversation belongs to. ![20240720-105540](https://private-user-images.githubusercontent.com/113153117/350658090-0f67f2f9-137a-43db-b876-73ff2de9e877.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0NTI0NTAsIm5iZiI6MTcyMTQ1MjE1MCwicGF0aCI6Ii8xMTMxNTMxMTcvMzUwNjU4MDkwLTBmNjdmMmY5LTEzN2EtNDNkYi1iODc2LTczZmYyZGU5ZTg3Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMFQwNTA5MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MDAyMDlkOTBlYmMzNDhjOWJlOWNmZTFlYTg2YWUxMGVkMzE2MmFkNjdlODFlYmMyNmY4ZTRlYzBhZGM0NTYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qw9EH3VMABqIMOxDdrU6hn_Q0VUahTGPluQvlui57xs)
> 
> Of course, they have been uploaded into https://huggingface.co/datasets/ll-13/FIT-RS/blob/main/FIT-RS_Instruction/train_data_of_each_individual_task.zip.

I'm sorry to interrupt again, but in conjunction with the article, I thought you proposed two benchmarks for testing, a FIT-RSFG (for test) and a FIT-RSRC (for test), but it seems that the only ones on huggingface are FIT-RS (for train) and FIT-RSRC, and there is no FIT-RSFG for FIT-RSFG for test.I'm not sure if I'm misunderstanding the division of the data.

**Comment by Luo-Z13** [comment]
> > > Can you please provide a dataset categorized by task? Like in the article. Right now this organization leads me to not know which task this one conversation belongs to. ![20240720-105540](https://private-user-images.githubusercontent.com/113153117/350658090-0f67f2f9-137a-43db-b876-73ff2de9e877.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0NTI0NTAsIm5iZiI6MTcyMTQ1MjE1MCwicGF0aCI6Ii8xMTMxNTMxMTcvMzUwNjU4MDkwLTBmNjdmMmY5LTEzN2EtNDNkYi1iODc2LTczZmYyZGU5ZTg3Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMFQwNTA5MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MDAyMDlkOTBlYmMzNDhjOWJlOWNmZTFlYTg2YWUxMGVkMzE2MmFkNjdlODFlYmMyNmY4ZTRlYzBhZGM0NTYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qw9EH3VMABqIMOxDdrU6hn_Q0VUahTGPluQvlui57xs)
> > 
> > 
> > Of course, they have been uploaded into https://huggingface.co/datasets/ll-13/FIT-RS/blob/main/FIT-RS_Instruction/train_data_of_each_individual_task.zip.
> 
> I'm sorry to interrupt again, but in conjunction with the article, I thought you proposed two benchmarks for testing, a FIT-RSFG (for test) and a FIT-RSRC (for test), but it seems that the only ones on huggingface are FIT-RS (for train) and FIT-RSRC, and there is no FIT-RSFG for FIT-RSFG for test.I'm not sure if I'm misunderstanding the division of the data.

You are right, the evaluation script for FIT-RSFG is being organized, and we will upload it soon.
