### ISSUE TITLE
什么时候完整的开源训练代码和模型

### ISSUE THREAD

**Issue by wwlaoxi** [Luo-Z13/SkySenseGPT#3]
您好，看到咱们团队的在遥感方向的大模型研究效果，很是厉害。想问一下微调代码和模型，什么时候开源了，到时候想测试验证一下，谢谢。

**Comment by Luo-Z13** [comment]
> 您好，看到咱们团队的在遥感方向的大模型研究效果，很是厉害。想问一下微调代码和模型，什么时候开源了，到时候想测试验证一下，谢谢。

您好，代码框架是与[LLaVA](https://github.com/haotian-liu/LLaVA)或[Geochat](https://github.com/mbzuai-oryx/geochat)一致的，模型权重后续会公开，目前完整数据集和评测代码都已公开，欢迎使用。
