### ISSUE TITLE
About License

### ISSUE THREAD

**Issue by mustansarfiaz** [Luo-Z13/SkySenseGPT#4]
Hi, 

Thank you for sharing the great work. I am wondering about the licensing.
Over GitHub, the license says it is [Apache 2.0 license](https://github.com/Luo-Z13/SkySenseGPT/blob/main/LICENSE).
However, over Hugging face it states: Creative Commons Attribution Non Commercial 4.0. [https://huggingface.co/datasets/ll-13/FIT-RS/tree/main/FIT-RSFG]

My question is that is it allowed to use for commercial purposes?

Regards
Mustansar

**Comment by Luo-Z13** [comment]
> Hi,
> 
> Thank you for sharing the great work. I am wondering about the licensing. Over GitHub, the license says it is [Apache 2.0 license](https://github.com/Luo-Z13/SkySenseGPT/blob/main/LICENSE). However, over Hugging face it states: Creative Commons Attribution Non Commercial 4.0. [https://huggingface.co/datasets/ll-13/FIT-RS/tree/main/FIT-RSFG]
> 
> My question is that is it allowed to use for commercial purposes?
> 
> Regards Mustansar

Thank you for your inquiry. The scripts (python code) in this repo are indeed open source under the Apache 2.0 license. The FIT-RS dataset hosted on Hugging Face is licensed under the Creative Commons Attribution Non Commercial 4.0 license, which means it is not allowed for commercial use.
