### ISSUE TITLE
数据集中用到公开的数据了吗？比如dota之类的

### ISSUE THREAD

**Issue by lyf6** [Luo-Z13/SkySenseGPT#5]

**Comment by Luo-Z13** [comment]
> _No description provided._

你好，FIT-RS数据集中不含DOTA这类已有数据集的数据，数据全部来源于遥感场景图生成数据集STAR(https://linlin-dev.github.io/project/STAR.html)

**Comment by dongwhfdyer** [comment]
这个数据集里并没有下载链接啊，很奇怪你们怎么下载数据的
