### ISSUE TITLE
Where is the image in the dataset?

### ISSUE THREAD

**Issue by dongwhfdyer** [Luo-Z13/SkySenseGPT#6]
I have downloaded the instruction dataset from huggingface. Where is the corresponding images?

**Comment by Luo-Z13** [comment]
> I have downloaded the instruction dataset from huggingface. Where is the corresponding images?

Images are in the `FIT-RS_Instruction` folder.

**Comment by dongwhfdyer** [comment]
<img width="1068" alt="mac_1732958509332" src="https://github.com/user-attachments/assets/92b08822-d1e5-466e-a43f-04f8d24ecc15">
Really？

**Comment by dongwhfdyer** [comment]
Now I found out.

**Comment by dongwhfdyer** [comment]
> > I have downloaded the instruction dataset from huggingface. Where is the corresponding images?
> 
> Images are in the `FIT-RS_Instruction` folder.

can you see my email? hope you can reply. thank you
